# Generated by Django 6.0 on 2026-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('TENANT_MANAGER', 'Tenant Manager'), ('TENANT_USER', 'Tenant User')], default='tenant_user', max_length=20),
        ),
    ]
