# Generated by Django 6.0 on 2026-02-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_number_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('account_locked', 'Account Locked'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('subscription_changed', 'Subscription Changed'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('document_shared', 'Document Shared')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TENANT_ADMIN', 'Tenant Admin'), ('TENANT_MANAGER', 'Tenant Manager'), ('TENANT_USER', 'Tenant User')], default='TENANT_USER', max_length=20),
        ),
    ]
