# Generated by Django 5.2.5 on 2026-02-23 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('tenant_id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('rag_enabled', models.BooleanField(default=True)),
                ('max_documents', models.IntegerField(default=100)),
                ('max_chunks_per_document', models.IntegerField(default=1000)),
                ('max_queries_per_day', models.IntegerField(default=1000)),
                ('chunk_size', models.IntegerField(default=500)),
                ('chunk_overlap', models.IntegerField(default=50)),
                ('retrieval_top_k', models.IntegerField(default=5)),
                ('relevance_threshold', models.FloatField(default=0.3)),
                ('llm_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('max_response_tokens', models.IntegerField(default=500)),
                ('temperature', models.FloatField(default=0.7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=63)),
                ('user_id', models.CharField(db_index=True, max_length=63)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='conversatio_tenant__1a8b8e_idx'), models.Index(fields=['created_at'], name='conversatio_created_694913_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('num_sources', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aichat_service.conversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=63)),
                ('title', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('indexing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('num_chunks', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_indexes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'indexing_status'], name='document_in_tenant__755929_idx'), models.Index(fields=['created_at'], name='document_in_created_3d40ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('relevance_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_in', to='aichat_service.documentindex')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='aichat_service.chatmessage')),
            ],
            options={
                'db_table': 'message_sources',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='RAGUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=63)),
                ('user_id', models.CharField(db_index=True, max_length=63)),
                ('queries_count', models.IntegerField(default=0)),
                ('documents_indexed', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rag_usage_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='rag_usage_s_tenant__eefb2f_idx'), models.Index(fields=['date'], name='rag_usage_s_date_358902_idx')],
                'unique_together': {('tenant_id', 'user_id', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_0a903c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['message'], name='message_sou_message_7c6b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['document'], name='message_sou_documen_b27637_idx'),
        ),
    ]
