# Generated by Django 6.0.1 on 2026-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentindex',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documentindex',
            name='indexing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
