# Generated by Django 6.0.1 on 2026-02-24 10:28

from django.db import migrations


def migrate_status(apps, schema_editor):
    DocumentIndex = apps.get_model('aichat_service', 'DocumentIndex')
    DocumentIndex.objects.filter(indexing_status='completed').update(indexing_status='indexed')

class Migration(migrations.Migration):

    dependencies = [
        ('aichat_service', '0002_alter_documentindex_file_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_status),
    ]
