# Generated by Django 5.2.5 on 2026-02-23 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=63)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_by_id', models.UUIDField(db_index=True)),
                ('is_public', models.BooleanField(default=False)),
                ('shared_with_ids', models.JSONField(blank=True, default=list)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('indexing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=50)),
                ('category_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doc_service_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='doc_service_tenant__c25e29_idx'), models.Index(fields=['tenant_id', 'uploaded_by_id'], name='doc_service_tenant__066fee_idx'), models.Index(fields=['tenant_id', 'is_indexed'], name='doc_service_tenant__b24721_idx'), models.Index(fields=['tenant_id', 'indexing_status'], name='doc_service_tenant__309280_idx'), models.Index(fields=['tenant_id', 'category_id'], name='doc_service_tenant__30beb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('delete', 'Delete'), ('share', 'Share'), ('update', 'Update'), ('upload', 'Upload')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'doc_service_documentaccesslog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_id', '-created_at'], name='doc_service_documen_ca88dd_idx'), models.Index(fields=['user_id', '-created_at'], name='doc_service_user_id_5e9c06_idx'), models.Index(fields=['document_id', 'action', '-created_at'], name='doc_service_documen_6155c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, max_length=63)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doc_service_documentcategory',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'parent_id'], name='doc_service_tenant__8485b8_idx'), models.Index(fields=['tenant_id', 'order'], name='doc_service_tenant__0d8862_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('chunk_index', models.IntegerField()),
                ('chunk_size', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doc_service_documentchunk',
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['document_id', 'chunk_index'], name='doc_service_documen_985d62_idx'), models.Index(fields=['document_id', 'embedding_status'], name='doc_service_documen_c1d244_idx')],
            },
        ),
    ]
