# Generated by Django 5.2.5 on 2026-02-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='indexing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=100),
        ),
    ]
